tilde_deadline_detector_node:
  ros__parameters:
    # input of e2e
    sensor_topics: [
      "/sensing/lidar/top/self_cropped/pointcloud_ex"
      ]
    # output of e2e
    target_topics: [
      "/control/trajectory_follower/control_cmd"
      ]
    # specify deadline ms for topics in target_topics order.
    # 0 means no deadline, and negative values are replaced by 0
    # deadline_ms corresponds to target_topics
    deadline_ms: [835]
    # parameters of debug messages
    show_performance: true
    print_report: true
    # print_pending_messages: true
